version: "3.9"
services:

  web:
    build: .
    volumes:
      - .:/egnet
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - '.env'
    environment:
      - REDIS_URL=redis://redis:6379/1
      
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - '.env'

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"